### ISSUE TITLE
[Bug] Autosave (qc/client.qc) relative path issues

### ISSUE THREAD

**Issue by m0rb** [progs-dump-dev/progs_dump#4]
The other day I ran into what I thought was originally a map bug on a recently released map that includes progs_dump (Cheesebase01.bsp)

It seems line 100 of client.qc is problematic on at least two engines; vkQuake 1.22.8 and quakespasm-spiked 2022-08-11 on Fedora 38 x86_64 in my case

The "echo Autosaving..." portion is causing a pattern match condition in host_cmd.c (line 1106); the engines test for ".." in order to prevent prevent two dots from appearing in a filename or path traversal

Not sure whether or not to yell at engine devs about this one but I figured it'd be a quick patch over on this side just to remove the periods at the end :)

Cheers

**Comment by dumptruckDS** [comment]
Thanks we'll get this fixed for the next release.
